import React, { useState } from 'react';
import { CalendarClock, AlertTriangle, Download, CalendarDays, Loader2 } from 'lucide-react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';

export default function DeadlineTracker() {
    const [formData, setFormData] = useState({ filing_date: new Date().toISOString().split('T')[0], case_type: 'Original Suit' });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);
    const [deadlines, setDeadlines] = useState([]);

    const handleSubmit = async () => {
        setLoading(true); setError(null); setDeadlines([]);
        try {
            const res = await axios.post('http://localhost:8000/deadline-tracker', formData);
            setDeadlines(res.data.deadlines);
        } catch (err) {
            setError(err.response?.data?.detail || err.message);
        }
        setLoading(false);
    };

    const downloadICal = () => {
        if (!deadlines.length) return;
        let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Lumina Copilot//EN\n";
        
        deadlines.forEach(d => {
            const dateStr = d.due_date.replace(/-/g, '') + "T090000Z";
            icsContent += "BEGIN:VEVENT\n";
            icsContent += `DTSTART:${dateStr}\n`;
            icsContent += `DTEND:${dateStr}\n`;
            icsContent += `SUMMARY:Deadline: ${d.name}\n`;
            icsContent += `DESCRIPTION:Source: ${d.source}. Generated by Lumina Copilot.\n`;
            icsContent += "END:VEVENT\n";
        });
        
        icsContent += "END:VCALENDAR";
        
        const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
        const link = document.createElement('a');
        link.href = window.URL.createObjectURL(blob);
        link.setAttribute('download', `Commercial_Deadlines_${formData.filing_date}.ics`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <div className="max-w-5xl mx-auto py-12 px-6">
            <h1 className="text-3xl font-black mb-8 flex items-center gap-3"><CalendarClock className="text-indigo-600" /> Commercial Deadlines</h1>
            
            <div className="bg-white rounded-2xl p-6 border shadow-sm mb-8 flex flex-col md:flex-row gap-6 items-end">
                <div className="flex-1 w-full">
                    <label className="block text-sm font-bold mb-2">Filing Date</label>
                    <input type="date" className="w-full p-3 border rounded-xl" value={formData.filing_date} onChange={e => setFormData({...formData, filing_date: e.target.value})} />
                </div>
                <div className="flex-1 w-full">
                    <label className="block text-sm font-bold mb-2">Case Type</label>
                    <select className="w-full p-3 border rounded-xl" value={formData.case_type} onChange={e => setFormData({...formData, case_type: e.target.value})}>
                        <option>Original Suit</option>
                        <option>Execution</option>
                        <option>Appeal</option>
                        <option>Arbitration</option>
                    </select>
                </div>
                <button onClick={handleSubmit} disabled={loading} className="py-3 px-8 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl flex items-center justify-center gap-2 transition md:w-auto w-full disabled:opacity-50 h-[50px]">
                    {loading ? <Loader2 className="animate-spin" /> : 'Calculate Deadlines'}
                </button>
            </div>

            {error && <div className="text-rose-600 text-sm bg-rose-50 p-4 rounded-xl flex items-center gap-2 mb-8"><AlertTriangle/>{error}</div>}

            <AnimatePresence mode="wait">
                {loading ? (
                    <div className="bg-white border rounded-2xl shadow-sm overflow-hidden animate-pulse">
                        <div className="p-6 border-b flex justify-between items-center bg-slate-50">
                            <div className="h-6 w-48 bg-slate-200 rounded-full" />
                            <div className="h-10 w-32 bg-slate-200 rounded-lg" />
                        </div>
                        <div className="p-6 space-y-4">
                            {[...Array(4)].map((_, i) => (
                                <div key={i} className="flex flex-col md:flex-row md:items-center justify-between p-4 border rounded-xl bg-white gap-4">
                                    <div className="space-y-2">
                                        <div className="h-5 w-48 bg-slate-100 rounded-full" />
                                        <div className="h-3 w-32 bg-slate-50 rounded-full" />
                                    </div>
                                    <div className="flex gap-4">
                                        <div className="h-10 w-24 bg-slate-100 rounded-lg" />
                                        <div className="h-10 w-24 bg-slate-100 rounded-lg" />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                ) : deadlines.length > 0 ? (
                    <motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} className="bg-white border rounded-2xl shadow-sm overflow-hidden">
                        <div className="p-6 border-b flex justify-between items-center bg-slate-50">
                            <h2 className="text-xl font-bold flex items-center gap-2"><CalendarDays className="text-indigo-600"/> Computed Timelines</h2>
                            <button onClick={downloadICal} className="flex items-center gap-2 px-4 py-2 bg-white border rounded-lg text-sm font-bold shadow-sm hover:bg-slate-50">
                                <Download size={16} /> Export .iCal
                            </button>
                        </div>
                        <div className="p-6 space-y-4">
                            {deadlines.map((d, i) => (
                                <div key={i} className="flex flex-col md:flex-row md:items-center justify-between p-4 border rounded-xl hover:shadow-md transition bg-white gap-4 relative overflow-hidden">
                                    <div className={`absolute left-0 top-0 bottom-0 w-1 ${d.urgency === 'red' ? 'bg-rose-500' : d.urgency === 'amber' ? 'bg-amber-500' : 'bg-emerald-500'}`} />
                                    <div className="pl-2">
                                        <h3 className="text-lg font-bold text-slate-800">{d.name}</h3>
                                        <p className="text-sm text-slate-500 mt-1 cursor-help group" title="Legal Source">
                                            {d.source}
                                        </p>
                                    </div>
                                    <div className="flex items-center gap-6 md:justify-end">
                                        <div className="text-right">
                                            <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Due Date</div>
                                            <div className="text-[15px] font-black">{d.due_date}</div>
                                        </div>
                                        <div className={`px-4 py-2 rounded-lg text-sm font-bold text-center min-w-[100px] ${
                                            d.urgency === 'red' ? 'bg-rose-100 text-rose-700' : 
                                            d.urgency === 'amber' ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'
                                        }`}>
                                            {d.days_remaining} Days
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </motion.div>
                ) : (
                    <div className="h-full min-h-[400px] flex flex-col items-center justify-center bg-nyaya-surface/30 border-2 border-dashed border-nyaya-border rounded-[2rem] text-center p-12">
                        <div className="w-16 h-16 bg-white border border-nyaya-border rounded-2xl flex items-center justify-center mb-6 shadow-sm text-nyaya-muted/40">
                            <CalendarClock size={32} />
                        </div>
                        <h3 className="text-xl font-bold text-nyaya-text mb-2">Automated Compliance</h3>
                        <p className="text-nyaya-muted max-w-sm leading-relaxed">
                            Select a filing date and case type above to auto-generate statutory deadlines under Order XV-A of the CPC.
                        </p>
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
}
